[phases.setup]
nixPkgs = ["python311", "cairo", "pango", "gdk-pixbuf", "glib", "shared-mime-info"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = ". .venv/bin/activate && sh entrypoint.sh"